### ISSUE TITLE
Query operation failed: In order to perform this operation a successful bind must be completed on the connection

### ISSUE THREAD

**Issue by douyu** [ldaptools/ldaptools#33]
I run the following code:
```
$repository = $ldap->getRepository('user');  
$repository->findOneBy(['username' => $username]);
```
then throws
```
exception 'LdapTools\Exception\LdapConnectionException' with message 'LDAP search failed. Diagnostic message: "000004DC: LdapErr: DSID-0C0906E8, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db1"' in /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Operation/Handler/QueryOperationHandler.php:128 Stack trace: #0 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Operation/Handler/QueryOperationHandler.php(60): LdapTools\Operation\Handler\QueryOperationHandler->processSearchResult(false, Array) #1 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Operation/Invoker/LdapOperationInvoker.php(167): LdapTools\Operation\Handler\QueryOperationHandler->execute(Object(LdapTools\Operation\QueryOperation)) #2 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Operation/Invoker/LdapOperationInvoker.php(86): LdapTools\Operation\Invoker\LdapOperationInvoker->getCacheOrHandlerResult(Object(LdapTools\Operation\QueryOperation), Object(LdapTools\Operation\Handler\QueryOperationHandler), NULL) #3 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Operation/Invoker/LdapOperationInvoker.php(58): LdapTools\Operation\Invoker\LdapOperationInvoker->executeOperation(Object(LdapTools\Operation\QueryOperation), NULL) #4 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Connection/LdapConnection.php(213): LdapTools\Operation\Invoker\LdapOperationInvoker->execute(Object(LdapTools\Operation\QueryOperation)) #5 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Query/LdapQuery.php(383): LdapTools\Connection\LdapConnection->execute(Object(LdapTools\Operation\QueryOperation)) #6 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Query/LdapQuery.php(412): LdapTools\Query\LdapQuery->getResultsFromLdap(Object(LdapTools\Operation\QueryOperation), 'object', Object(LdapTools\Schema\LdapObjectSchema), 'user') #7 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Query/LdapQuery.php(256): LdapTools\Query\LdapQuery->getResultsForAliases('object') #8 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Query/LdapQuery.php(164): LdapTools\Query\LdapQuery->execute('object') #9 /mnt/hgfs/projects/hodor-server/vendor/ldaptools/ldaptools/src/LdapTools/Object/LdapObjectRepository.php(73): LdapTools\Query\LdapQuery->getSingleResult() #10 /mnt/hgfs/projects/hodor-server/src/Service/LdapApi.php(25): LdapTools\Object\LdapObjectRepository->findOneBy(Array) #11
```

it's seems user bind not successfull in here, but i use `authenticate` function bind ok

**Comment by ChadSikorra** [comment]
What does your configuration look like (for the config class you're passing to the LdapManager)? Is this OpenLDAP or AD?

**Comment by douyu** [comment]
use openldap in my code: 

```
list($host, $port) = explode(':', $ldapconf['servers'][$name]);
$config = new Configuration();
$domain = new DomainConfiguration($ldapconf['domain']);
$domain->setBaseDn($ldapconf['basedn']);
$domain->setServers([$host]);
$domain->setPort($port);
$domain->setUsername($ldapconf['username']);
$domain->setPassword($ldapconf['password']);
$domain->setLazyBind(true);
$domain->setLdapType('openldap');
$config->addDomain($domain);
$config->setDefaultDomain($ldapconf['domain']);
new LdapManager($config);
```

**Comment by ChadSikorra** [comment]
Does a `var_dump($ldapconf);` show that the username/password are actually set? It could potentially be something to do with the `lazy_bind` option, but it's not an issue I have ever encountered. Does switching that to `false` change anything?

**Comment by douyu** [comment]
`$ldapconf` is ok, I try the difference `lazy_bind` mode but this exception is still exists.
this is a outsource work, I will track it in a few days and give you further information

**Comment by ChadSikorra** [comment]
Hmm, ok. Still trying to think of possible scenarios where this could happen. I still wonder if the username/password are being set. It could be binding anonymously somehow if they aren't set right. Another test would be to set paging to false in the config to see if that makes any difference.

**Comment by douyu** [comment]
change the `ldap_type` from `openldap` to `ad` solved this problem，but I can't tell why and what the difference between `openldap` and `ad`.

**Comment by ChadSikorra** [comment]
The main difference is the bind format and the schema (off the top of my head anyway). Are you using the full dn for the bind username?

**Comment by douyu** [comment]
No, just username. 

Configure as fellow avoid this exception but can't find any result
```
$domain = new DomainConfiguration('domain');
$domain->setBindFormat('%username%@%domainname%');
$domain->setLdapType('openldap');
```

**Comment by ChadSikorra** [comment]
Is the LDAP you're connecting to really Active Directory? I'm not aware of OpenLDAP supporting a `username@domain.local` sort of format for a bind. Though I have not tested against Samba based OpenLDAP setup. In that case you would probably really want to specify `ad` for the LDAP type.

**Comment by douyu** [comment]
The server is adapted Active Directory, extend other protocol and feature. I use `ad` for query and `openldap` for authenticate, works fine.
