### ISSUE TITLE
Exchange Mailbox creation  problems

### ISSUE THREAD

**Issue by shak18** [ldaptools/ldaptools#52]
Hi, i want to enable mailbox on certain users of my AD (no all will have mailbox) so far this library its been working great but cant seem to do this, i have the following in my code:

// im ommiting the query of ldap for the user as its fine as it can be. ($username)

````
$server = $ldap->buildLdapQuery()
            ->from(LdapObjectType::EXCHANGE_SERVER)
            ->where(['guid' => $server_guid])
            ->getLdapQuery()
            ->getSingleResult();
````

thr result is this (ok so far):

````
Object(LdapTools\Object\LdapObject)#161 (4) {
  ["functions":protected]=>
  array(6) {
    [0]=>
    string(3) "has"
    [1]=>
    string(3) "get"
    [2]=>
    string(3) "set"
    [3]=>
    string(6) "remove"
    [4]=>
    string(3) "add"
    [5]=>
    string(5) "reset"
  }
  ["type":protected]=>
  string(14) "ExchangeServer"
  ["attributes":protected]=>
  array(6) {
    ["name"]=>
    string(9) "SRVMAILB6"
    ["version"]=>
    array(1) {
      [0]=>
      string(47) "Exchange Server 2010 SP3 (Build 14.03.0123.004)"
    }
    ["dn"]=>
    string(206) "CN=SRVMAILB6,CN=Servers,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=GobiernoYucatan,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=gobierno1,DC=yucatan,DC=gob,DC=mx"
    ["guid"]=>
    array(1) {
      [0]=>
      string(36) "4bfcf0b7-cb1b-44f1-a3df-7ff6b78c9711"
    }
    ["legacyExchangeDn"]=>
    string(110) "/o=GobiernoYucatan/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=SRVMAILB6"
    ["roles"]=>
    array(1) {
      [0]=>
      array(1) {
        [0]=>
        string(15) "MailboxDatabase"
      }
    }
  }
  ["batches":protected]=>
  object(LdapTools\BatchModify\BatchCollection)#181 (2) {
    ["batches":protected]=>
    array(0) {
    }
    ["dn":protected]=>
    string(206) "CN=SRVMAILB6,CN=Servers,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=GobiernoYucatan,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=gobierno1,DC=yucatan,DC=gob,DC=mx"
  }
}
`````

then the database:

````
$database = $ldap->buildLdapQuery()
            ->from(LdapObjectType::EXCHANGE_DATABASE)
            ->where(['guid' => $database_guid])
            ->getLdapQuery()
            ->getSingleResult();

````

again everithing is fine

````
object(LdapTools\Object\LdapObject)#112 (4) {
  ["functions":protected]=>
  array(6) {
    [0]=>
    string(3) "has"
    [1]=>
    string(3) "get"
    [2]=>
    string(3) "set"
    [3]=>
    string(6) "remove"
    [4]=>
    string(3) "add"
    [5]=>
    string(5) "reset"
  }
  ["type":protected]=>
  string(16) "ExchangeDatabase"
  ["attributes":protected]=>
  array(3) {
    ["name"]=>
    string(8) "BDYUCVIP"
    ["dn"]=>
    string(207) "CN=BDYUCVIP,CN=Databases,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=GobiernoYucatan,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=gobierno1,DC=yucatan,DC=gob,DC=mx"
    ["guid"]=>
    array(1) {
      [0]=>
      string(36) "262887b1-3531-4f7b-80b1-05cb3187181b"
    }
  }
  ["batches":protected]=>
  object(LdapTools\BatchModify\BatchCollection)#109 (2) {
    ["batches":protected]=>
    array(0) {
    }
    ["dn":protected]=>
    string(207) "CN=BDYUCVIP,CN=Databases,CN=Exchange Administrative Group (FYDIBOHF23SPDLT),CN=Administrative Groups,CN=GobiernoYucatan,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=gobierno1,DC=yucatan,DC=gob,DC=mx"
  }
}

````

then i try the sample code to enable the mail box

````
$mailbox = $ldap->createLdapObject(LdapObjectType::EXCHANGE_MAILBOX_USER)
            ->with([
                'username' => $username,
                'password' => $password,
                'mailboxDatabase' => $database,
                'mailboxServer' => $server
            ])
            ->in( Config::get('LDAP_BASE_DN'))
            ->execute();

````

and here is where nightmare begins, at first i start gettin errors when the class was trying to parse certain parameters toLdap like so:

````
"Unable to convert value \"Default Policy\" to a objectGuid for attribute \"recipientPolicies\""
"Unable to convert value \"All Mailboxes(VLV)\" to a dn for attribute \"showInAddressBooks\"
"Unable to convert value \"Default Role Assignment Policy\" to a dn for attribute \"rbacPolicy\""

````

all comming from the same place 

````
"#0 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\AttributeConverter\\ConvertValueToDn.php(66): LdapTools\\AttributeConverter\\ConvertValueToDn->getAttributeFromLdapQuery('Default Role As...', 'dn')",
                "#1 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\BaseValueResolver.php(234): LdapTools\\AttributeConverter\\ConvertValueToDn->toLdap('Default Role As...')",
                "#2 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\BaseValueResolver.php(154): LdapTools\\Resolver\\BaseValueResolver->doConvertValues('rbacPolicy', Array, 'toLdap', NULL)",
                "#3 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\AttributeValueResolver.php(92): LdapTools\\Resolver\\BaseValueResolver->getConvertedValues('Default Role As...', 'rbacPolicy', 'toLdap')",
                "#4 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\AttributeValueResolver.php(71): LdapTools\\Resolver\\AttributeValueResolver->convert(Array)",
                "#5 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\ArrayHydrator.php(313): LdapTools\\Resolver\\AttributeValueResolver->toLdap()",
                "#6 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\ArrayHydrator.php(174): LdapTools\\Hydrator\\ArrayHydrator->convertValuesToLdap(Array)",
                "#7 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\OperationHydrator.php(114): LdapTools\\Hydrator\\ArrayHydrator->hydrateToLdap(Array)",
                "#8 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\OperationHydrator.php(80): LdapTools\\Hydrator\\OperationHydrator->hydrateAddOperation(Object(LdapTools\\Operation\\AddOperation))",
                "#9 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\OperationHydrator.php(56): LdapTools\\Hydrator\\OperationHydrator->hydrateOperation(Object(LdapTools\\Operation\\AddOperation))",
                "#10 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Object\\LdapObjectCreator.php(272): LdapTools\\Hydrator\\OperationHydrator->hydrateToLdap(Object(LdapTools\\Operation\\AddOperation))",
                "#11 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Object\\LdapObjectCreator.php(252): LdapTools\\Object\\LdapObjectCreator->getAddOperation()",
                "#12 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\App\\Directorio\\Controllers\\DirectorioController.php(210): LdapTools\\Object\\LdapObjectCreator->execute()"
````

as i wasnt able to determine what was wrong here i modified the method convert of `AttributeValueResolver.php` like this:

````
protected function convert(array $attributes, $toLdap = true)
    {
        $direction = ($toLdap) ? 'toLdap' : 'fromLdap';
        
        foreach ($attributes as $attribute => $values) {
            // No converter, but the value should still be encoded.
            if($attribute == 'rbacPolicy' || 
                $attribute == 'recipientPolicies' ||
                $attribute == 'showInAddressBooks' 
                ) { continue; }
````
 and then i got this:

````
"Unable to determine msExchVersion version number for build \"06.05\" and attribute \"version\""
````

i know my server is an exchange 2010 but the auto parameter seems to get the version wrong, again i modified for debug the file `ConvertExchangeObjectVersion.php` specificly the `$buildMap` array to:

````
protected $buildMap =[
        '08' => '2007',
        '14' => '2010',
        '06.05' => '2010',
        '15.00' => '2013',
        '15.01' => '2016',
    ];

````

just to get another one:

````
"To send a password to AD you need to enable either TLS or SSL in your configuration."
````

at:
````
                "#0 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\AttributeConverter\\EncodeWindowsPassword.php(32): LdapTools\\AttributeConverter\\EncodeWindowsPassword->validateConfiguration()",
                "#1 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\BaseValueResolver.php(234): LdapTools\\AttributeConverter\\EncodeWindowsPassword->toLdap('')",
                "#2 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\BaseValueResolver.php(154): LdapTools\\Resolver\\BaseValueResolver->doConvertValues('password', Array, 'toLdap', NULL)",
                "#3 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\AttributeValueResolver.php(96): LdapTools\\Resolver\\BaseValueResolver->getConvertedValues('', 'password', 'toLdap')",
                "#4 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Resolver\\AttributeValueResolver.php(71): LdapTools\\Resolver\\AttributeValueResolver->convert(Array)",
                "#5 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\ArrayHydrator.php(313): LdapTools\\Resolver\\AttributeValueResolver->toLdap()",
                "#6 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\ArrayHydrator.php(174): LdapTools\\Hydrator\\ArrayHydrator->convertValuesToLdap(Array)",
                "#7 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\OperationHydrator.php(114): LdapTools\\Hydrator\\ArrayHydrator->hydrateToLdap(Array)",
                "#8 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\OperationHydrator.php(80): LdapTools\\Hydrator\\OperationHydrator->hydrateAddOperation(Object(LdapTools\\Operation\\AddOperation))",
                "#9 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Hydrator\\OperationHydrator.php(56): LdapTools\\Hydrator\\OperationHydrator->hydrateOperation(Object(LdapTools\\Operation\\AddOperation))",
                "#10 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Object\\LdapObjectCreator.php(272): LdapTools\\Hydrator\\OperationHydrator->hydrateToLdap(Object(LdapTools\\Operation\\AddOperation))",
                "#11 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\vendor\\ldaptools\\ldaptools\\src\\LdapTools\\Object\\LdapObjectCreator.php(252): LdapTools\\Object\\LdapObjectCreator->getAddOperation()",
                "#12 D:\\SOFTWARE\\Xampp\\htdocs\\GIT\\buzones-correo\\App\\Directorio\\Controllers\\DirectorioController.php(210): LdapTools\\Object\\LdapObjectCreator->execute()"
````

at this point i feel kind of stuck im not sure that enabling ssl will do anything besides the pain of dealing with the server people im not even sure it will work, besides mi ideal scenario is that the password for the mailbox will be the same as the ldap user password, and im not able to query that, so far i was passing an empty string.

can someone tell me if this is a bug, something im doing wrong or anything else please

**Comment by ChadSikorra** [comment]
I have not had time to focus on this library lately, so I'm not sure how much I can assist. But there are quite a few things that come to mind.

1. Are you trying to mail enable an already existing user? If that is the case, then this library does not yet support that functionality. It can create new AD users as mail enabled Exchange users though.
2. What language was Exchange installed as on the server end? English? I feel like the default queries might be failing to locate stuff if this is not the case. Just a hunch though.
3. It's actually an AD requirement that if you need to do an operation that involves a password, it will force SSL / TLS. Although this can be disabled via the registry on a DC, no one administering AD should EVER do that. You can enable SSL/TLS for this library and then just disable certificate validation (not recommended, but better than no SSL at all). See the config documentation for how to get that working.

**Comment by ChadSikorra** [comment]
Another thought, it's also possible the policies were renamed. You can query for them the same way as the Exchange Database, and then set them on the user when you create them.

**Comment by shak18** [comment]
> I have not had time to focus on this library lately, so I'm not sure how much I can assist. But there are quite a few things that come to mind.
> 
> 1. Are you trying to mail enable an already existing user? If that is the case, then this library does not yet support that functionality. It can create new AD users as mail enabled Exchange users though.
> 2. What language was Exchange installed as on the server end? English? I feel like the default queries might be failing to locate stuff if this is not the case. Just a hunch though.
> 3. It's actually an AD requirement that if you need to do an operation that involves a password, it will force SSL / TLS. Although this can be disabled via the registry on a DC, no one administering AD should EVER do that. You can enable SSL/TLS for this library and then just disable certificate validation (not recommended, but better than no SSL at all). See the config documentation for how to get that working.

1. Yes that was my goal, but what about deleting the account an recreating it as mail enabled?
2. is in english
3 and extra. ill give a shot 

anyway thaks for the tips even if im not able to get this to work and fallback to the powershell script this library was a great addition to my project, again thanks

**Comment by ChadSikorra** [comment]
Deleting the account, saving existing user properties, then re-applying to a new mailbox user while creating them would work. Though if the user has individual permissions applied anywhere (like on a fileserver or something), then those would break.

My guess is that your Exchange policy names are different from the defaults, or have been changed. In that instance you would need to explicitly search for and use them. Like for the RBAC and Recipient Policy:

```php
$recipientPolicies = $ldap->buildLdapQuery()
            ->from(LdapObjectType::EXCHANGE_RECIPIENT_POLICY)
            ->getLdapQuery()
            ->getResult();

$rbacPolicies = $ldap->buildLdapQuery()
            ->from(LdapObjectType::EXCHANGE_RBAC_POLICY)
            ->getLdapQuery()
            ->getResult();
```

Then when creating the user you would assign the RBAC policy to the `rbacPolicy` attribute and the recipient policy to `recipientPolicies`.

Regarding the Exchange Version, it would seem that you still have an Exchange Server 2003 system in your environment, or it was never removed properly and is still in AD. As version 6.5 is for Exchange 2003. You could get around that by specifically referencing the Exchange Version when creating the user: `['version' => 'v2010']`. 

You can verify the version it pulls from your environment automagically by running this:

```php
var_dump($query->select('serialNumber')
            ->where(['objectClass' => 'msExchExchangeServer'])
            ->andWhere($query->filter()->present('serverRole'))
            ->setBaseDn('%_configurationnamingcontext_%')
            ->setSizeLimit(1)
            ->getLdapQuery()
            ->getSingleScalarOrNullResult());
```

That's where it's finding some kind of Exchange Server 2003 info.
